### ISSUE TITLE
How to use "context query parameter or option"

### ISSUE THREAD

**Issue by mkstix6** [brokenmass/advanced-image-loader#3]
I might be messing up or something might be broken. I'm not sure.
The readme documentation is already great, thank you, but I could use some advice on context query/option if you have time. Please and thank you.

---

### From the readme:

"[path] the path of the resource relative to the context query parameter or option."

I'd like to use the [path] option. At the moment it's giving me the path from my hard drive root.

I've tried to add a context option but I haven't seen any changes yet.

I've tried adding to the loader:

`loader: 'advanced-image-loader?context=./src'`

Also, tried to add context in the options:

```
options: {
    width: 1280,
    srcset: [320, 640, 960, 1280, 1920],
    quality: 90,
    placeholder: 32,
    context: './src',
    name: '[path][name]-[width]',
}
```

…but I still get the hard drive root 😞. I'd greatly appreciate any suggestions?

Thanks for your work on the loader.
…and thanks for reading.

---

## More information on my use case:

I am using this advanced-image-loader with the pug templating engine and pug-html-loader to output a static site. advanced-image-loader seems to resize the images and replace the image `src`s perfectly 🌟.

I'm constructing the `srcset` by hand because I don't think or expect I can get this loader to write the `srcset` whilst I'm using pug.

🤔 In the future I think I would drop pug and try to use JS or a JS library (Vue/React/etc…) for templating, I think this would make my life with webpack easier. I'm still fairly new to webpack so I haven't quite yet managed to let go of my HTML first mentality.

**Comment by brokenmass** [comment]
I think I have to modify the code to support the context option. in the meantime you can use a function in the options to generate the name.

The function receives an object in the format:
```
{
  "buffer": <image data buffer?
  "info": {
    "format": string <format of the output image>,
    "width": integer <width of the output image>,
    "height": integer <height of the output image>,
    "channels": integer <number of collor channels of the output image>,
    "size": integer <filesize of the output image>
  },
  "options": object <the configuration option>,
  "resourcePath": string <absolute path of the input image>
}
```
and has to return a string.

In your case you should read the resourcePath to calculate the relative path.

something like:

```
const path = require('path');

const context = path.join(__dirname, 'src');
// ...
options: {
    width: 1280,
    srcset: [320, 640, 960, 1280, 1920],
    quality: 90,
    placeholder: 32,
    name: (data) => {
        const path = path.parse(data.resourcePath);
        const relativeDir = path.relative(context, path.dir);
        const fileName = path.name + '-' + data.info.width + path.ext;
        return path.join(relativeDir, fileName);
    }
}
```

be very careful, I HAVE NOT TESTED the above lines. I wrote them while sipping a coffee after lunch :D
